application: d-ablage
version: dev
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /gaetk/.*
  script: lib/gaetk/gaetk/defaulthandlers.py

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
  
- url: /_ah/login_required
  script: lib/gaetk/gaetk/login.py

- url: /logout
  script: lib/gaetk/gaetk/login.py

- url: .*
  script: main.py

skip_files:
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?CHANGES
- ^(.*/)?LICENSE
- ^(.*/)?Makefile
- ^(.*/)?requirements\.txt
- ^(.*/)?setup.py
- ^(.*/)?(docs?|tests?)/.*
- ^(.*/)?README.*
- ^(.*/)?lib/google_appengine/.*
- ^(.*/)?lib/gaetk/google/.*
- ^(.*/)?testenv/.*
- ^(.*/)?pythonenv/bin/.*
- ^(.*/)?pythonenv/include/.*
- ^(.*/)?lib/gae-sessions/(demo|demo-with-google-logins)/.*
- ^(.*/)?pythonenv/lib/python2.5/site-packages/setuptools.*
- ^(.*/)?pythonenv/lib/python2.5/site-packages/pip.*
- ^(.*/)?pythonenv/lib/python2.5/(encodings|lib-dynload)/.*
